/* Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Architecture defines (unchanged, system-dependent) */
#define ARCH_X86 1
#define ARCH_X86_64 1

/* Version-specific defines */
#ifdef GEGL_05
  #define GETTEXT_PACKAGE "gegl-0.5"
#else
  #define GETTEXT_PACKAGE "gegl-0.4"
#endif

/* Stability flag (stable for both 0.4 and 0.5 releases) */
#undef GEGL_UNSTABLE

/* System-detected feature defines (unchanged from your original) */
#define HAVE_EXECINFO_H
#define HAVE_FSYNC
#undef HAVE_GEXIV2
#undef HAVE_LUA
#define HAVE_MALLOC_TRIM
#undef HAVE_MRG
#define HAVE_STRPTIME
#define HAVE_UNISTD_H
